name: release
on:
  release:
    types: [created]

jobs:
  ci:
    name: Publish Hex Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.5.0
        with:
          otp-version: 25
          elixir-version: 1.14.4
          experimental-otp: true
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh  
      - name: Build
        run: |
          bash scripts/deploy.sh
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}